spring.application.name=JYso
server.port=8080
spring.main.web-application-type=servlet
spring.main.banner-mode=off

logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.apache=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.eclipse=ERROR
logging.level.org.jboss=ERROR
